import 'package:flutter/material.dart';
import 'package:learning_apis/home.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Learning API',
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          appBar: AppBar(
            centerTitle: true,
            title: const Text(
              'First API Call 🤩',
              style: TextStyle(fontWeight: FontWeight.w300, fontSize: 25),
            ),
          ),
          body: const HomePage(),
        ));
  }
}

/*
Steps I have performed to use API 

-->Most imp added http package dependencies to yaml.
1. took the fake data from 'https://jsonplaceholder.typicode.com/posts'
2. Tested the API is giving response properly or not from 'https://web.postman.co/'
3. Autogenerated the code for API from 'https://app.quicktype.io/'. Just copied the body from the postman that was tested and paste.
4.Created a List to  getData using async & await.

*/
